version: 0.0
os: linux
files:
  - source: demo
    destination: /var/www/my-nuxt-app
file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/my-nuxt-app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: demo/scripts/app_stop.sh
      timeout: 30
      runas: ubuntu

  AfterInstall:
    - location: demo/scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: demo/scripts/app_start.sh
      timeout: 60
      runas: ubuntu
